apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-artifact-to-ibm-cloud-functions
spec:
  params:
    - name: path-to-manifest-file
      description: The path to the yaml file to deploy within the git source
      default: manifest.yaml
    - name: ibm-cloud-region
      description: Region where cluster is located
    - name: api-url
      description: API URL for interacting with IBM Cloud
      default: cloud.ibm.com
  workspaces:
    - name: source
  steps:
    - name: deploy-app
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.15
      env:
        - name: IBMCLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: apikey
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $(params.api-url) -r $(params.ibm-cloud-region);
          ibmcloud version;
          ibmcloud plugin list;
          ibmcloud plugin update cloud-functions;
          ibmcloud plugin list;
          ibmcloud target --cf;
          ibmcloud fn deploy -m $(workspaces.source.path)/$(params.path-to-manifest-file);
          ibmcloud fn action get -r helloTekton;
